name: NaturalBank
version: '${version}'
main: id.naturalsmp.naturalbank.NaturalBank
api-version: '1.21'
authors: [ Natural Dev Creative ]
description: Advanced banking system for Minecraft servers
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - Essentials
  - EconomyPlus
  - CMI
load: POSTWORLD
commands:
  naturalbank:
    aliases: [nbank, bank, bp, bankplus]

  banktop:
    aliases: [btop]